### ISSUE TITLE
Removing old PR data.

### ISSUE THREAD

**Issue by singhayushh** [DSCKGEC/kgec-summer-of-code#12]
### The issue:
Using the github api, all of the Pull Requests are being fetched for the given repositories. Some of them date back to previous iteration of KSoC. So when this data is being used to create the leaderboard, past year's contributions are also being counted for.

### Fix:
Updating the date-time filter being used before the api call. You can see a variable named startTime in the `api/github.go` file. Update the date value to whatever date we want to start considering contributions from.

**Comment by singhayushh** [comment]
@anilphiyak617 do you want to work on this?

**Comment by anilphiyak617** [comment]
ok sure 👍

**Comment by singhayushh** [comment]
Had to work on some sections of the code so I edited this too
Marking as done and closing this issue.
