### ISSUE TITLE
Header and footer - work needed

### ISSUE THREAD

**Issue by singhayushh** [DSCKGEC/kgec-summer-of-code#2]
Hello, 
In the header and footer sections, the links to other sub-pages haven't been added and we are looking for contributions to the same. 

#### Instructions
- Files to be edited: `header.html` and `footer.html` under `views` directory
- The header has a button that points to the project page or the dashboard page. Links for the same are to be added
- The footer currently has dummy data. It is to be replaced with the links to various social media accounts and developer profiles of DSC KGEC as well as the subpages of the website - one column for each.

**Comment by himanshu007-creator** [comment]
HI, i would like to work on this issue

**Comment by singhayushh** [comment]
Hello @himanshu007-creator 
This issue is for our team members working on the site. 

Public issues will be posted 5th May onward. 
Thanks a lot for showing your interests!
